# Generated by Django 4.2 on 2024-01-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_home_disc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='footer_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='mail',
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='img',
            field=models.ImageField(blank=True, default='/static/images/default-avatar-icon.jpg', null=True, upload_to='images/trainer'),
        ),
    ]
